### ISSUE TITLE
Unmatched double quotation preventing smooth parsing

### ISSUE THREAD

**Issue by hammady** [JamesAHammerton/arxivDeduplicationDataset#1]
Thanks for this useful dataset. I found that in line 251549 of `arXiv-docs`, there is an unmatched double quotation in the title which prevents parsers (tried node-js [csv parser](https://www.npmjs.com/package/csv-parse)) from parsing this line. Removing it fixes parsing:

    251549     " Discrete Approaches to Quantum Gravity in Four Dimensions     Living Reviews in Relativity    [Renate Loll]      1998    arxiv:gr-qc/9805049

Should be:

    251549      Discrete Approaches to Quantum Gravity in Four Dimensions     Living Reviews in Relativity    [Renate Loll]      1998    arxiv:gr-qc/9805049

**Comment by JamesAHammerton** [comment]
Thanks for spotting this. In my own work, I simply read each line in as a string and split it on tabs and that worked despite the problem you raise here. I suspect adding a matching quotation at the end of the field would also work. However part of my aim in creating this dataset was to include all the forms of noise that were present in the data and this unmatched double quotation mark is part of that noise. I'm guessing the fix would be to deploy a csv writer to write the date in a form that can be parsed but preserves the unmatched quotation. I'll have a think and get onto this tomorrow.

**Comment by hammady** [comment]
I beg to differ here. The noise in the data should be isolated from the noise in the correct representation of the data. While the former is expected, the latter should be correct to be parseable in different languages. The CSV standard format dictates that rows having new lines inside fields should be quoted (how would you handle this case in your approach that reads it line by line?). Any quotes inside fields should be escaped (as in \\"). Yes the original data could have unmatched quotes and new lines, but that should not corrupt its formal representation.

**Comment by JamesAHammerton** [comment]
Re: newlines - if I recall correctly (this was some years ago), given the way the original source for the dataset was processed this was not an issue - the titles had been preprocessed to convert white space to spaces. 

I'm not quite sure what your disagreement is. I was suggesting that I rewrite the data using a csv writer to preserve the fact that there's an extraneous double quotation mark in the title field of this particular record but to otherwise still be parseable - I'd expect it to escape the quotation mark somehow. Are you disagreeing with that approach?

**Comment by hammady** [comment]
I agree with what you said. However, there is no need for rewriting the whole file, just escaping the single quotation would make it parseable. My disagreement was on introducing parse errors as being part of dirty data. Anyway, that's your call at the end :)

**Comment by JamesAHammerton** [comment]
I tried parsing the file using python's csv reader configured for tab separation and got the same problem. I've fixed it now and uploaded a new .zip. I renamed the files in the archive to all have .tsv suffixes but the same names as before.

I've made sure that python's csv reader thinks it's properly formatted, let me know if you find any problems with the new version.

**Comment by hammady** [comment]
Cool. Thanks for fixing this.
